
// This file has been generated by the GUI designer. Do not modify.

public partial class MainWindow
{
	private global::Gtk.VBox vbox1;
	private global::Gtk.HBox hbox2;
	private global::Gtk.Label GameLabel;
	private global::Gtk.ComboBox SelectedGame;
	private global::Gtk.Fixed fixed92;
	private global::Gtk.ProgressBar DownloadProgress;
	private global::Gtk.ScrolledWindow GtkScrolledWindow;
	private global::Gtk.TextView Log;
	private global::Gtk.Button LaunchButton;
	private global::Gtk.Label Timer;
	
	protected virtual void Build ()
	{
		global::Stetic.Gui.Initialize (this);
		// Widget MainWindow
		this.Name = "MainWindow";
		this.Title = global::Mono.Unix.Catalog.GetString ("MainWindow");
		this.WindowPosition = ((global::Gtk.WindowPosition)(4));
		this.BorderWidth = ((uint)(3));
		// Container child MainWindow.Gtk.Container+ContainerChild
		this.vbox1 = new global::Gtk.VBox ();
		this.vbox1.Name = "vbox1";
		this.vbox1.Spacing = 6;
		// Container child vbox1.Gtk.Box+BoxChild
		this.hbox2 = new global::Gtk.HBox ();
		this.hbox2.Name = "hbox2";
		this.hbox2.Spacing = 6;
		// Container child hbox2.Gtk.Box+BoxChild
		this.GameLabel = new global::Gtk.Label ();
		this.GameLabel.Name = "GameLabel";
		this.GameLabel.Ypad = 1;
		this.GameLabel.LabelProp = global::Mono.Unix.Catalog.GetString ("Selected Game");
		this.GameLabel.UseMarkup = true;
		this.hbox2.Add (this.GameLabel);
		global::Gtk.Box.BoxChild w1 = ((global::Gtk.Box.BoxChild)(this.hbox2 [this.GameLabel]));
		w1.Position = 0;
		w1.Expand = false;
		w1.Fill = false;
		// Container child hbox2.Gtk.Box+BoxChild
		this.SelectedGame = global::Gtk.ComboBox.NewText ();
		this.SelectedGame.AppendText (global::Mono.Unix.Catalog.GetString ("Game1"));
		this.SelectedGame.AppendText (global::Mono.Unix.Catalog.GetString ("Test"));
		this.SelectedGame.Name = "SelectedGame";
		this.SelectedGame.Active = 0;
		this.hbox2.Add (this.SelectedGame);
		global::Gtk.Box.BoxChild w2 = ((global::Gtk.Box.BoxChild)(this.hbox2 [this.SelectedGame]));
		w2.Position = 1;
		w2.Expand = false;
		w2.Fill = false;
		this.vbox1.Add (this.hbox2);
		global::Gtk.Box.BoxChild w3 = ((global::Gtk.Box.BoxChild)(this.vbox1 [this.hbox2]));
		w3.Position = 0;
		w3.Expand = false;
		w3.Fill = false;
		// Container child vbox1.Gtk.Box+BoxChild
		this.fixed92 = new global::Gtk.Fixed ();
		this.fixed92.Name = "fixed92";
		this.fixed92.HasWindow = false;
		// Container child fixed92.Gtk.Fixed+FixedChild
		this.DownloadProgress = new global::Gtk.ProgressBar ();
		this.DownloadProgress.WidthRequest = 650;
		this.DownloadProgress.HeightRequest = 50;
		this.DownloadProgress.Name = "DownloadProgress";
		this.DownloadProgress.Text = global::Mono.Unix.Catalog.GetString ("Waiting..");
		this.fixed92.Add (this.DownloadProgress);
		global::Gtk.Fixed.FixedChild w4 = ((global::Gtk.Fixed.FixedChild)(this.fixed92 [this.DownloadProgress]));
		w4.X = 3;
		w4.Y = 383;
		// Container child fixed92.Gtk.Fixed+FixedChild
		this.GtkScrolledWindow = new global::Gtk.ScrolledWindow ();
		this.GtkScrolledWindow.Name = "GtkScrolledWindow";
		this.GtkScrolledWindow.ShadowType = ((global::Gtk.ShadowType)(1));
		// Container child GtkScrolledWindow.Gtk.Container+ContainerChild
		this.Log = new global::Gtk.TextView ();
		this.Log.WidthRequest = 440;
		this.Log.HeightRequest = 300;
		this.Log.CanFocus = true;
		this.Log.Name = "Log";
		this.Log.Editable = false;
		this.Log.CursorVisible = false;
		this.Log.WrapMode = ((global::Gtk.WrapMode)(3));
		this.GtkScrolledWindow.Add (this.Log);
		this.fixed92.Add (this.GtkScrolledWindow);
		global::Gtk.Fixed.FixedChild w6 = ((global::Gtk.Fixed.FixedChild)(this.fixed92 [this.GtkScrolledWindow]));
		w6.X = 10;
		w6.Y = 22;
		// Container child fixed92.Gtk.Fixed+FixedChild
		this.LaunchButton = new global::Gtk.Button ();
		this.LaunchButton.WidthRequest = 150;
		this.LaunchButton.HeightRequest = 150;
		this.LaunchButton.CanFocus = true;
		this.LaunchButton.Events = ((global::Gdk.EventMask)(512));
		this.LaunchButton.Name = "LaunchButton";
		this.LaunchButton.UseUnderline = true;
		this.LaunchButton.Label = global::Mono.Unix.Catalog.GetString ("Launch");
		this.fixed92.Add (this.LaunchButton);
		global::Gtk.Fixed.FixedChild w7 = ((global::Gtk.Fixed.FixedChild)(this.fixed92 [this.LaunchButton]));
		w7.X = 497;
		w7.Y = 204;
		// Container child fixed92.Gtk.Fixed+FixedChild
		this.Timer = new global::Gtk.Label ();
		this.Timer.Name = "Timer";
		this.Timer.LabelProp = global::Mono.Unix.Catalog.GetString ("0");
		this.fixed92.Add (this.Timer);
		global::Gtk.Fixed.FixedChild w8 = ((global::Gtk.Fixed.FixedChild)(this.fixed92 [this.Timer]));
		w8.X = 489;
		w8.Y = 18;
		this.vbox1.Add (this.fixed92);
		global::Gtk.Box.BoxChild w9 = ((global::Gtk.Box.BoxChild)(this.vbox1 [this.fixed92]));
		w9.Position = 1;
		this.Add (this.vbox1);
		if ((this.Child != null)) {
			this.Child.ShowAll ();
		}
		this.DefaultWidth = 661;
		this.DefaultHeight = 505;
		this.Show ();
		this.DeleteEvent += new global::Gtk.DeleteEventHandler (this.OnDeleteEvent);
	}
}
